In [2]:
import torch 
from torch import nn

net=nn.Sequential(nn.Linear(20,16),nn.ReLU(),nn.Linear(16,1))
X=torch.rand(2,20)
net(X)

tensor([[0.1022],
        [0.1027]], grad_fn=<AddmmBackward0>)

参数访问 

In [4]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.0886,  0.0862,  0.1562, -0.2012, -0.2137,  0.1912,  0.1724, -0.1329,
         -0.0737,  0.0609,  0.0444, -0.2248,  0.2055, -0.1456,  0.1248, -0.0319]])), ('bias', tensor([0.0845]))])


In [7]:
print(type(net[2].bias))

<class 'torch.nn.parameter.Parameter'>


访问所有参数

In [9]:
print(*[(name,param.shape) for name,param in net[0].named_parameters()])

('weight', torch.Size([16, 20])) ('bias', torch.Size([16]))


In [10]:
print(*[(name,param.shape) for name,param in net.named_parameters()])

('0.weight', torch.Size([16, 20])) ('0.bias', torch.Size([16])) ('2.weight', torch.Size([1, 16])) ('2.bias', torch.Size([1]))


In [12]:
net.named_parameters()

<generator object Module.named_parameters at 0x0000018009E94C10>

In [14]:
net.state_dict()['2.weight'].data

tensor([[ 0.0886,  0.0862,  0.1562, -0.2012, -0.2137,  0.1912,  0.1724, -0.1329,
         -0.0737,  0.0609,  0.0444, -0.2248,  0.2055, -0.1456,  0.1248, -0.0319]])

内置初始化

In [18]:
def init_normal(m):
    if type(m) ==nn.Linear:
        nn.init.normal_(m.weight,mean=0,std=0.01)
        #normal_中下划线在nn中为替换函数，将传入的数替换
        #nn.init模块中包含大量做初始化的函数
        nn.init.zeros_(m.bias)
net.apply(init_normal)
#net.apply()函数对net中所有module调用传入的参数对应的函数
net[0].weight.data[0],net[0].bias.data[0]

(tensor([ 3.2105e-03, -2.0115e-03,  1.3736e-02, -1.4064e-02, -7.7435e-03,
         -3.1567e-04,  1.4853e-02, -1.5274e-02,  7.6698e-03, -8.6655e-05,
          1.3160e-02,  1.4735e-02, -1.0834e-02,  1.6535e-02,  1.1150e-02,
          1.2416e-02, -5.1178e-03, -1.2653e-03, -5.5394e-03,  8.2856e-03]),
 tensor(0.))