In [ ]:
不带参数的自定义层

In [4]:
import torch
import torch.nn.functional as F
from torch import nn

class Centeredlayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self,X):
        return X-X.mean()
layer=Centeredlayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net=nn.Sequential(nn.Linear(8,128 ),Centeredlayer())
X=torch.randn(4,8)
net(X)

tensor([[-0.1895,  0.2527, -0.2429,  0.0944, -0.5920, -0.4186, -0.0645,  0.6482,
          0.3855,  0.5327, -0.0685, -0.2548,  0.2154, -0.7982,  0.7101,  0.3433,
          0.6097,  1.0595,  0.6721, -0.1906,  0.3147,  0.1606,  0.9995,  0.7855,
         -0.7218,  0.5754, -0.5460,  0.3569,  0.1622,  0.3779, -0.9233,  0.8655,
          0.0297, -0.8235,  0.8256, -0.9247,  0.2361,  0.5686, -1.1592,  0.6921,
         -0.4595,  0.4069, -0.5557,  1.0975,  1.4926,  0.2029,  0.2515, -0.6816,
          0.4169, -0.2538,  0.3895, -0.2727, -0.3557,  0.2577,  0.1639, -0.0788,
          0.0878, -0.7910,  0.8068,  0.6213, -0.4340, -0.0178,  0.7500, -0.5088,
          1.6829,  0.7140,  0.8774,  0.9584,  0.7922, -0.5603,  1.0102,  0.5239,
         -1.0580, -0.3635,  0.6520, -0.1045, -0.2690,  0.4551, -0.5831,  1.1185,
          0.1813, -0.3199, -0.3507,  0.8232, -0.1017,  0.2603, -1.3116,  0.5517,
          0.9681, -0.1610,  0.0337, -0.0666, -0.0712,  1.0466,  1.0182, -0.5430,
         -0.0551, -1.0141,  

带参数的层

层中的参数为nn.Parameter类的实例

In [7]:
type(net[0].weight)

torch.nn.parameter.Parameter

In [8]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
        
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)
    
dense=MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[-0.8705, -1.0465,  0.0150],
        [ 0.6011, -1.4182, -0.9062],
        [-1.1453, -0.6900, -0.1873],
        [-2.9209,  0.5472, -1.2840],
        [-0.1369,  0.6667, -0.9593]], requires_grad=True)

In [9]:
dense(torch.randn(2,5))

tensor([[1.2611, 0.2884, 0.7417],
        [4.2700, 0.0000, 2.5759]])