In [1]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
torch.save(x,'x-file')

x2=torch.load('x-file')
x2

tensor([0, 1, 2, 3])

## 加载和保存模型参数

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.out=nn.Linear(256,10)
    def forward(self,X):
        return self.out(F.relu(self.hidden(X)))

net=MLP()
X=torch.randn((2,20))
Y=net(X)
Y

tensor([[ 0.2785, -0.1525, -0.0522,  0.2163,  0.3295, -0.3574, -0.0564, -0.2737,
         -0.0743, -0.0865],
        [ 0.1578,  0.5366,  0.2388,  0.0575,  0.5420, -0.1200, -0.8350, -0.2847,
         -0.3120,  0.0524]], grad_fn=<AddmmBackward0>)

将模型的参数储存为一个叫做‘mlp.params'的文件

In [9]:
torch.save(net.state_dict(),'mlp.params')

In [10]:
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)

In [11]:
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])